services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  db:
    image: postgres

volumes:
  uploads: